### ISSUE TITLE
Превращение пешки

### ISSUE THREAD

**Issue by Dunissimo** [antonyanwm/Chess#3]
Когда пешка доходит до края доски, то она не становится ферзём/другой фигурой. Думаю, вы об этом знаете, но всё же

**Comment by antonyanwm** [comment]
Добавил релиз. Теперь дается выбор, и вы можете выбрать фигуру из списка. Спасибо вам!

**Comment by KarlenNersisyan** [comment]
@Dunissimo 👍

**Comment by KarlenNersisyan** [comment]
Done
